# Configuration for Travis-CI continuous integration.
#
# Copyright 2017, 2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

dist: bionic
language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y krb5-config libkrb5-dev libtest-pod-perl perl
env: AUTHOR_TESTING=1 C_TAP_VERBOSE=1
script: ./bootstrap && ./configure && make warnings && make check

branches:
  except:
    - /^debian\/.*/
    - pristine-tar
    - /^upstream\/.*/
